#!/bin/bash
oc whoami --show-context
serviceToLookFor=$(echo $1)
function exists_in_list() {
    LIST=$1
    DELIMITER=$2
    VALUE=$3
    echo $LIST | tr "$DELIMITER" '\n' | grep -q "$VALUE"
}
projects=$(oc get projects -o template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
eval "arr=($projects)"
echo "Servicen du leter etter ligger i prosjekt: "
for p in "${arr[@]}"; do
    services=$(oc get svc -n $p -o template --template '{{range .items}}{{.metadata.name}} {{end}}')
    if exists_in_list "$services" " " $serviceToLookFor; then
        echo "$p"
    fi
 done
